version: '3'

services:
  nginx: 
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    ports:
      - "${APP_PORT}:80/tcp"
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:z

  frontend:
    container_name: frontend
    build: ./front-ui
    restart: always
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - BASE_URL=http://api:3000/
      - BROWSER_BASE_URL

  api:
    container_name: api
    build: ./central-api
    restart: always
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=fsp
      - DB_USER=fsp
      - DB_PASS
      - REQUEST_TIMEOUT_THRESHOLD

  db:
    container_name: db
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=fsp
      - POSTGRES_USER=fsp
      - POSTGRES_PASSWORD=${DB_PASS}
