version: '3'

services:

  traefik:
    container_name: traefik
    image: traefik:v2.5
    privileged: true
    depends_on:
      - api
      - frontend
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=/traefik-dynamic.yml

      # Let's Encrypt
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json

      # Listen for https on 443, and http on 80 which just redirects to https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certresolver=letsencrypt
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      
    ports:
      - 443:443
      - 80:80
      - 127.0.0.1:9091:8080

    volumes:
      - fsp-letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

    configs:
      - traefik-dyanmic.yml

  frontend:
    container_name: frontend
    image: ghcr.io/file-share-platform/front-ui:main
    restart: always
    depends_on:
      - api
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - BASE_URL=http://api:3000/
      - BROWSER_BASE_URL=https://${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.middlewares=security-headers@file

  api:
    container_name: api
    image: ghcr.io/file-share-platform/central-api:main
    restart: always
    depends_on:
      - db
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=fsp
      - DB_USER=fsp
      - DB_PASS
      - REQUEST_TIMEOUT_THRESHOLD
      - BROWSER_BASE_URL=https://${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.middlewares=security-headers@file, api-headers@file

  db:
    container_name: db
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=fsp
      - POSTGRES_USER=fsp
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - fsp-pgdata:/var/lib/postgresql/data

configs:
  traefik-dynamic.yml:
    file: ./traefik-dynamic.yml

volumes:
  fsp-pgdata:
    external: true
  fsp-letsencrypt: